homepage/home/urls.py
from django.conf.urls import url

from . import views

urlpatterns =[
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^user/$', views.user_home, name='user_home'),
    url(r'^user_scan/$', views.user_home_scan, name='user_home_scan'),
    url(r'^directupload/$', views.user_upload_direct, name='user_upload_direct'),
    url(r'^user_procedure_flatbed/$', views.user_procedure_flatbed, name='user_procedure_flatbed'),
    url(r'^user_procedure_feeder/$', views.user_procedure_feeder, name='user_procedure_feeder'),
    url(r'^doc_info_feeder/$', views.doc_info_feeder, name='doc_info_feeder'),
    url(r'^doc_info_flatbed/$', views.doc_info_flatbed, name='doc_info_flatbed'),
    url(r'^scan_upload_feeder/$', views.user_upload_scan_feeder, name='user_upload_scan_feeder'),
    url(r'^scan_upload_flatbed/$', views.user_upload_scan_flatbed, name='user_upload_scan_flatbed'),
    url(r'^result/$', views.doc_result, name='doc_result'),
    url(r'^error_page/$', views.error_page, name='error_page'),
]

homepage/homepage/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^$', RedirectView.as_view(url='/home/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homepage/home/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
    document = models.FileField(upload_to='documents/')

homepage/home/forms.py
from django import forms
from .models import Document

# class DocumentForm(forms.Form):
#     doc_title = forms.CharField(max_length=250)
#     doc_type = forms.CharField(max_length=10)
#     doc_pages = forms.IntegerField()

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document',)

    # def __str__(self):
        # return "Title: %s, Type: %s, Pages: %d" % (self.doc_title, self.doc_type, self.doc_pages)

homepage/home/views.py
from __future__ import unicode_literals

from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from os.path import dirname, exists, isdir, realpath, isfile, join
import glob
import pdb

from .plagscan import login_user, plagscan_upload
from .forms import DocumentForm
# from .picam import capture_images
from .ocr import read_typewritten_img, read_handwritten_img
from .utils import SCANNED_FILES_DIR, create_dir, format_list, generate_pdf
from time import sleep

login_validation = False
doc_type = ""
doc_title = ""
doc_pages = 0

def index(request):
    global login_validation
    login_validation = False
    print(login_validation)
    return render(request, 'index.html')

def login(request):
    global login_validation
    login_validation = False
    if request.method == 'GET':
        login_validation = False
        return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST.get('username','')
        password = request.POST.get('pwd', '')
        if login_user(username, password):
            request.session['username'] = username
            request.session['password'] = password
            login_validation = True
            return render(request, 'user_home.html')

        else:
            # TODO: Invalid username password popup
            messages.warning(request, 'Login failed! Please enter a valid username and password, or check your internet connection and try again!')
            return render(request, 'login.html')

def user_home(request):
    global login_validation
    login_validation = False
    if login_validation:
        return render(request, 'user_home.html')
    else:
        return render(request, 'error_page.html')

def user_home_scan(request):
    global login_validation
    print(login_validation)
    if login_validation:
        return render(request, 'user_home_scan.html')
    else:
        return render(request, 'error_page.html')

def doc_info_flatbed(request):
    print('doc_info_flatbed')
    print(login_validation)
    if login_validation:
        if request.method == 'GET':
            return render(request, 'doc_info_flatbed.html')
        elif request.method == 'POST':
            global doc_type
            global doc_title
            global doc_pages
            doc_type= request.POST.get('doc_type','')
            doc_title = request.POST.get('doc_title', '')
            doc_pages = request.POST.get('doc_pages','')

            if not create_dir(doc_title):
                messages.error(request, 'Folder already exists!')
                return render(request, 'doc_info_flatbed.html')
            else:
                messages.success(request, 'New folder created! Folder location: ' + SCANNED_FILES_DIR)
                return render(request, 'user_procedure_flatbed.html', {})
    else:
        return render(request, 'error_page.html')

def doc_info_feeder(request):
    print(login_validation)
    if login_validation:
        if request.method == 'GET':
            return render (request, 'doc_info_feeder.html', {})
        elif request.method == 'POST':
            global doc_type 
            global doc_title
            global doc_pages
            doc_type= request.POST.get('doc_type','')
            doc_title = request.POST.get('doc_title', '')
            doc_pages = request.POST.get('doc_pages','')

            if not create_dir(doc_title):
                messages.error(request, 'Folder already exists!')
                return render(request, 'doc_info_feeder.html')
            else:
                messages.success(request, 'New folder created! Folder location: ' + SCANNED_FILES_DIR)
                return render(request, 'user_procedure_feeder.html', {})
    else:
        return render(request, 'error_page.html')

def user_procedure_flatbed(request):
    print(login_validation)
    if login_validation:
        return render(request, 'user_procedure_flatbed.html')
    else:
        return render(request, 'error_page.html')

def user_procedure_feeder(request):
    print(login_validation)
    if login_validation:
        return render(request, 'user_procedure_feeder.html')
    else:
        return render(request, 'error_page.html')

def user_upload_scan_flatbed(request):
    print('user_upload_scan_flatbed')
    if login_validation:
        if request.method == 'GET':
            #Start scanning: motors move one cycle
            # capture_images(SCANNED_FILES_DIR + doc_title + '/', doc_pages)
            print('Finish Capturing images')
            pdb.set_trace()
            recognized_text = []
            # for file in glob.glob(SCANNED_FILES_DIR + doc_title + '/*.jpg'):
            #     if doc_type == 'T_Written':
            #         unformatted_list = read_typewritten_img(file)
            #         recognized_text.append(format_list(unformatted_list))
            #     else:
            #         pass
                    # unformatted_list = read_handwritten_img(file)
                    # recognized_text.append(
                    # format_list(unformatted_list))
            generate_pdf(recognized_text, doc_title)
            print("PDF generated")
            return render(request, 'user_upload_scan_flatbed.html')
        elif request.method == 'POST':
            print('POST')
            content = dirname(realpath(__file__)) + "/Documents/" + doc_title + "/" + doc_title + ".pdf"
            if plagscan_upload(content):
                messages.success(request, 'Files upload completed!')
                return render(request, 'doc_result.html')
            else:
                messages.error(request, 'Files failed to upload! Try again.')
                return render(request, 'user_upload_scan_flatbed.html')
    else:
        return render(request, 'error_page.html')

def user_upload_scan_feeder(request):
    if login_validation:
        if request.method == 'GET':
            print('GET')
            #Start scanning: motors move based on doc_pages
            # capture_images(SCANNED_FILES_DIR + doc_title + '/', doc_pages)
            print('Finish Capturing images')
            pdb.set_trace()
            recognized_text = []
            # for file in glob.glob(SCANNED_FILES_DIR + doc_title + '/*.jpg'):
            #     if doc_type == 'T_Written':
            #         unformatted_list = read_typewritten_img(file)
            #         recognized_text.append(format_list(unformatted_list))
            #     else:
            #         pass
                    # unformatted_list = read_handwritten_img(file)
                    # recognized_text.append(
                    # format_list(unformatted_list))
            generate_pdf(recognized_text, doc_title)
            print("PDF generated")
            return render(request, 'user_upload_scan_feeder.html')
        elif request.method == 'POST':
            print('POST')
            content = dirname(realpath(__file__)) + "/Documents/" + doc_title + "/" + doc_title + ".pdf"
            if plagscan_upload(content):
                messages.success(request, 'Files upload completed!')
                return render(request, 'doc_result.html')
            else:
                messages.error(request, 'Files failed to upload! Try again.')
                return render(request, 'user_upload_scan_feeder.html')
    else:
        return render(request, 'error_page.html')

def user_upload_direct(request):
    if login_validation:
        if request.method == 'GET':
            print('GET')
            return render(request, 'user_upload_direct.html')
        elif request.method == 'POST':
            print('POST')
            form = DocumentForm(request.POST, request.FILES)
            if form.is_valid():
                print('FORM IS VALID')
                form.save()
                return redirect('')
        else:
            print('INVALID FORM')
            print(request.FILES)
            form = DocumentForm()
        return render(request, 'user_upload_direct.html',{'form':form})
    else:
        return render(request, 'error_page.html')

def doc_result(request):
    global login_validation
    if login_validation:
        return render(request, 'doc_result.html')
        login_validation = False
    else:
        return render(request, 'error_page.html')

def error_page(request):
    global login_validation
    login_validation = False
    return render(request, 'error_page.html')

homepage/home/templates/borders.html
{% load static %}
<html>
<head>
    <link rel="icon" type="image/png" href="{% static 'images/pup-logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="header">
            <div class="col-xs-4">
                <a href="{% url 'home:index' %}"><img src="{% static 'images/pup-logo.png' %}"></a>
                <!-- <a href="http://127.0.0.1:8080/home/"><img src="{% static 'images/pup-logo.png' %}"></a> -->
            </div>
            <div class="col-xs-8">
                <h3>Polytechnic University of the Philippines</h3>
                <h4>Computer Engineering Department</h4>
                <h4>Anti-Plagiarism Device</h4>
            </div>
        </div>
    </div>
</div>
<div class="content">
    {% block content %}
    {% endblock %}
</div>

<footer>
    
</footer>
</body>
</html>

homepage/home/templates/doc_info_feeder.html
{% extends 'borders.html' %}
{% block title %}Document Information{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="login">
                    <div class="card card-outline-primary">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <!-- {{form}} -->
                            <div style="margin-bottom: 15px">
                                <input type="radio" id="doc_type"
                                    name="doc_type" value="H_Written" required>Handwritten Document<br>
                                <input type="radio" id="doc_type"
                                    name="doc_type" value="T_Written">Computerized Document
                            </div>
                            <div class="form-group form-inline">
                                <label for="title">Document Name:</label>
                                    <input type="text" class="form-control" id="doc_title"
                                        name="doc_title" required>
                                <label for="pages">Number of Pages:</label>
                                <input type="number" class="form-control" name="doc_pages" id="doc_pages" min="1" max="20" required>
                            </div>
                            <button type="submit" class="btn btn-outline-primary">Submit</button><br>
                        </form>
                    </div><!-- card card-outline-primary -->
                </div><!-- login -->
            </div><!-- col-md-12 -->
        </div><!-- row -->
    </div><!-- container -->
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}

homepage/home/templates/doc_info_flatbed.html
{% extends 'borders.html' %}
{% block title %}Document Information{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="login">
                    <div class="card card-outline-primary">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <!-- {{form}} -->
                            <div style="margin-bottom: 15px">
                                <input type="radio" id="doc_type"
                                    name="doc_type" value="H_Written" required>Handwritten Document<br>
                                <input type="radio" id="doc_type"
                                    name="doc_type" value="T_Written">Computerized Document
                            </div>
                            <div class="form-group form-inline">
                                <label for="title">Document Name:</label>
                                    <input type="text" class="form-control" id="doc_title"
                                        name="doc_title" required>
                            </div>
                            <button type="submit" class="btn btn-outline-primary">Submit</button><br>
                        </form>
                    </div><!-- card card-outline-primary -->
                </div><!-- login -->
            </div><!-- col-md-12 -->
        </div><!-- row -->
    </div><!-- container -->
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}

homepage/home/templates/doc_result.html
{% extends 'borders.html' %}
{% block title %}Result{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="home-option">
                <div class="col-xs-12">
                    <div class="card card-outline-primary">
                        <p>Display Result here!</p>
                        <center>
                            <a href="{% url 'home:index' %}" type="submit" class="btn btn-outline-primary btn-inst"><p>Finish</p></a>
                        </center>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div> 
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}

homepage/home/templates/error_page.html
{% extends 'borders.html' %}
    {% block title %}Error{% endblock %}
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="home">
                        <h1 style="font-weight: 900;">Page not found!</h1><br>
                        <a href="{% url 'home:index' %}" type="submit" class="btn btn-outline-primary btn-inst"><p>Return to home</p></a>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

homepage/home/templates/index.html
{% extends 'borders.html' %}
    {% block title %}Home{% endblock %}
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="home">
                        <h1 style="font-weight: 900;">Welcome!</h1><br>
                        <a href="{% url 'home:login' %}" class="btn btn-outline-primary"><p>Next!</p></a>
                        <!-- <a href="http://127.0.0.1:8080/home/user/" class="btn btn-outline-primary"><p>Next!</p></a> -->
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

homepage/home/templates/login.html
{% extends 'borders.html' %}
{% block title %}Login{% endblock %}
{% block content %}
{% load static %}
    <div class="container">
        <div class="row">
            <div class="login">
                <div class="card card-outline-primary text-center">
                    <img class="plagscan-logo" src="{% static 'images/plagscan-logo.png' %}">
                    <form action="" method="POST">
                    <!-- <form action="{% url 'home:user_home' %}" method="POST"> -->
                        {% csrf_token %}
                        <!-- {{form}} -->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="username">Username:</label>
                                <input type="text" class="form-control"
                                        name="username" id="username" required>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="pwd">Password:</label>
                                <input type="password" class="form-control" 
                                        name="pwd" id="pwd" required>
                            </div>
                        </div>
                        <!-- <div class="col-sm-12">
                            <div class="form-group">
                                <label for="domain">Enter Domain Name:</label>
                                <input type="text" value="" class="form-control" id="domain" required>
                            </div>
                        </div> -->
                        <button type="submit" class="btn btn-outline-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div> 
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}

homepage/home/templates/user_home.html
{% extends 'borders.html' %}
{% block title %}User{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="home-option">
                <div class="col-xs-6 text-center">
                    <div class="card card-outline-primary">
                        <a href="{% url 'home:user_home_scan' %}" type="submit" class="btn btn-outline-primary">
                            <i class="fa fa-file" aria-hidden="true"></i>
                        </a>
                        <!-- <a href="http://127.0.0.1:8080/home/document_title/" type="submit" class="btn btn-outline-primary"><i class="fa fa-file" aria-hidden="true"></i></a> -->
                        <p>Scan a Document</p>
                    </div>
                </div>
                <div class="col-xs-6 text-center">
                    <div class="card card-outline-primary">
                        <a href="{% url 'home:user_upload_direct' %}" class="btn btn-outline-primary" type="submit"><i class="fa fa-upload" aria-hidden="true"></i></i></a>
                        <!-- <a href="{% url 'home:login' %}" class="btn btn-outline-primary" type="submit"><i class="fa fa-upload" aria-hidden="true"></i></i></a> -->
                        <!-- <a href="http://127.0.0.1:8080/home/login/" class="btn btn-outline-primary" type="submit"><i class="fa fa-upload" aria-hidden="true"></i></i></a> -->
                        <p>Direct Upload (Softcopy)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

homepage/home/templates/user_home_scan.html
{% extends 'borders.html' %}
{% block title %}Scan a document{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="home-option">
                <div class="col-xs-6 text-center">
                    <div class="card card-outline-primary">
                        <a href="{% url 'home:doc_info_flatbed' %}" type="submit" class="btn btn-outline-primary"><i class="fa fa-book" aria-hidden="true"></i></a>
                        <!-- <a href="http://127.0.0.1:8080/home/document_title/" type="submit" class="btn btn-outline-primary"><i class="fa fa-file" aria-hidden="true"></i></a> -->
                        <p>Flatbed</p>
                    </div>
                </div>
                <div class="col-xs-6 text-center">
                    <div class="card card-outline-primary">
                        <a href="{% url 'home:doc_info_feeder' %}" class="btn btn-outline-primary" type="submit"><i class="fa fa-print" aria-hidden="true"></i></i></a>
                        <!-- <a href="{% url 'home:login' %}" class="btn btn-outline-primary" type="submit"><i class="fa fa-upload" aria-hidden="true"></i></i></a> -->
                        <!-- <a href="http://127.0.0.1:8080/home/login/" class="btn btn-outline-primary" type="submit"><i class="fa fa-upload" aria-hidden="true"></i></i></a> -->
                        <p>Feeder</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

homepage/home/templates/user_procedure_feeder.html
{% extends 'borders.html' %}
{% block title %}Feeder Procedure{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="home-option">
                <div class="col-xs-12">
                    <div class="card card-outline-primary">
                        <p>Instructions:</p>
                        <ol type="1">
                            <li>Insert the document on the paper feeder properly in landscape orientation.</li>
                            <li>Make sure that the pages are facing down.</li>
                            <li>Click 'Next' to start scanning.</li>
                        </ol>
                        <center>
                            <a href="{% url 'home:user_upload_scan_feeder' %}" type="submit" class="btn btn-outline-primary btn-inst"><p>Next</p></a>
                        </center>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div> 
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}

homepage/home/templates/user_procedure_flatbed.html
{% extends 'borders.html' %}
{% block title %}Flatbed Procedure{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="home-option">
                <div class="col-xs-12">
                    <div class="card card-outline-primary">
                        <p>Instructions:</p>
                        <ol type="1">
                            <li>Place the document on the flatbed glass facing down.</li>
                            <li>Make sure that the document is in proper orientation. </li>
                            <li>Click 'Next' to start scanning.</li>
                        </ol>
                        <center>
                            <a href="{% url 'home:user_upload_scan_flatbed' %}" type="submit" class="btn btn-outline-primary btn-inst"><p>Next</p></a>
                        </center>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div> 
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}

homepage/home/templates/user_upload_direct.html
{% extends 'borders.html' %}
{% block title %}Upload{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="home-option">
                <div class="col-xs-12">
                    <div class="card card-outline-primary">
                        <p><b>Upload your files in pdf form!</b></p>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <center>
                                <input class="user_upload_direct_input file" type="file" name="myfile"><br>
                                <button type="submit" class="btn btn-outline-primary btn-inst"><p>Submit</p></button>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div> 
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}

homepage/home/templates/user_upload_scan_feeder.html
{% extends 'borders.html' %}
{% block title %}Upload from feeder{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="home-option">
                <div class="col-xs-12">
                    <div class="card card-outline-primary">
                        <p>Done Scanning!</p><br>
                        <p>Your files are now ready to upload.</p>
                        <form action="" method="POST">
                        {% csrf_token %}
                            <center>
                                <button type="submit" class="btn btn-outline-primary btn-inst"><p>Upload</p></button>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    
    {% if messages %}
        {% for message in messages %}
            <div id="myModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <center>{{ message }}</center>
                        </div>
                    </div>
                </div> 
            </div>
        {% endfor %}
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#myModal").modal('show');
        });
    </script>
{% endblock %}